cloud:
  aws:
    s3:
      bucket: cqrebucket
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instance-profile: true
      access-key: ENC(6KkkjuJa5SWcphOoT/JutUe+WvdgLhEe5OQYOxr0eJU=)
      secret-key: ENC(4XWCX4d5aaziqBOcJUF88vG10V+5pFsnUclRagNgfnQhQMkDR9piwTq3ou/j/sENv0UdBUOXT4g=)

spring:
  datasource:
    url: ENC(IbgO4T1dbSt7DeJamWTLzDR0nc9An4jXlGk1YFtPzTAO1M34vztf7RjtxXhYwI2VNLlTOeYtVVS4vNtfeYn3pH1M9xlObf/CNPcEsccuWAphzbyFboAuLiL1/FF4gmvZ2qJOa9U7JtL9fsnkYugJ/Ne6c57/Ts+i+U1UiSlgRwk9E8Ou0X9jnQ==)
    username: ENC(r+gbLBAEXbtJLPBhCi4ubA==)
    password: ENC(fd0maz6hwV97RhTkhFjcR0wbK2O9X9sB)
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      location: C:\Users\leejihoon\Desktop\CQRE\temp
      enabled: true

  jpa:
    hibernate:
      ddl-auto: none
    database: mysql
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
        naming:
          physical-strategy: org.hibernate.boot.model.naming.MySQL5InnoDBDialect

  thymeleaf:
    cache: false
    prefix: classpath:/templates

  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(QT8z7IwD3d7RKZODrW48Qjd2G5XzCtm9+XDPNysu7RKXVe5laxxTiA==)
    password: ENC(CmxUNn05HrRvA5VFKnsJrI8biJWv6K0w)
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(FkqTYHx0nfQe+TAGM6bHxiTBs5ffIyFDDrouPKBKbj1BWlsRkos0sU5CA9RtPjcBOEu/Q9Y5XH2CZUTe458M8cnxefsVx9e6/m+p3ghPIpyT4i/11uqLxg==)
            client-secret: ENC(sMtgjllxwfojYJbyyks5GyNnN4AOOQFfKZjGu3hBfhAs+5nb4zQmvA==)
            scope: profile,email
          facebook:
            client-id: ENC(kt0ynjPj/xwCEUqOui1ugEHZwdwLZNVo)
            client-secret: ENC(nmyqeuQkoBNU3m1uGJyd7T9djkV2N/uPK/DX/7kDIpq0eZqqnJnAWHUIh6ip5wAV)
            scope: email,public_profile
          naver:
            client-id: ENC(7S/dZDwxkxqiLvyYPOiQjsOT61DNedBWy9WVZ2/2xos=)
            client-secret: ENC(fzDakgYUHGSD7+M6u3agyU2hgQzhbDF5)
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
            scope: name,email
            client-name: Naver
          kakao:
            client-id: ENC(Ty4sihty3/25Q7ecz/ZguQ2/vz0vMBm24jpybD9UA+4HSBaoZwKgAZe55eU5hdy7)
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
            scope: profile,account_email
            client-name: Kakao

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jasypt:
  encryptor:
    bean: jasyptStringEncryptor